### ISSUE TITLE
[epic] React Resource editor (+ multiple resources at once, table schema, CKAN integration)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#1]
New React-based app/component for creating and editing one or more resources add adding to a Dataset. This replaces CKAN classic resource create and edit but ONLY for ckan inistances using `ckanext-external-storage` (which we hope will soon be most or all of our CKAN instances).

NB: we can assume dataset already exists. In later evolution we will extend to include dataset creation etc.

Design features:

* Use React
* (Resource) Schema will now stored as attribute `schema` on a resource (as per Frictionless pattern) rather than in Data Dictionary and associated with DataStore.
* Inside React we use Frictionless spec for describing resources, table schemas etc (and convert to CKAN format at boundary)

## Job Stories

TODO - see https://tech.datopian.com/publish/

## Mockups

![](https://i.imgur.com/UQdDunG.png)

![](https://i.imgur.com/AZ7D5JQ.png)

[Figma link](https://www.figma.com/file/WAIncZHwSfKN0DNJM4fPxL/Uploader?node-id=0%3A1)

## Acceptance

In a CKAN classic instance using ckanext-external-storage the resource editor is a React app and:

* [x] I can upload resources (direct to cloud)
* [x] I can edit resource metadata
* [x] I can edit the table schema
* [x] This is all saved to CKAN MetaStore
* [x] This works for editing existing resources i.e. the React app can also load / get given an existing resource
* [ ] I have a migration script for migrating existing CKAN instances (i.e moving data dictionary info to `schema` attribute)

Leftovers

* [x] Fixing up DataStore to retrieve table schema info from resource object **Is this needed? If people who upgrade to `ckanext-external-storage` also upgrade to AirCan there is no need. => Probably no need**

## Status

```mermaid
graph TD

choose[Select File or Link File]

choose --> select[Select file to upload]
choose --> link[Link file to upload]

select --> openfile(Open File => data.js Resource/File object)
openfile --> upload[Upload in Background + Upload UI]
openfile --> metaeditor[Metadata Editor]
openfile -.if tabular.-> schemaeditor[Schema Editor]
upload --completes--> save
metaeditor --no errors--> save
schemaeditor --no errors--> save

link -. if you can open or just create default.-> openfile

cancel[Cancel this resource]

classDef done fill:#21bf73,stroke:#333,stroke-width:1px;
classDef nearlydone fill:lightgreen,stroke:#333,stroke-width:1px;
classDef inprogress fill:orange,stroke:#333,stroke-width:1px;
classDef next fill:lightblue,stroke:#333,stroke-width:1px;

class choose,upload,metaeditor,select done;
class select,nearlydone nearlydone;
class schemaeditor,inprogress inprogress;
class openfile next;
```

## Tasks

v0.1 JS app (macro component) for adding a single resource to a dataset with file upload

* [x] Stub the React application 1d #2
* [x] Set up tests 1d #3 
* [x] Setup storybook #4
* [x] Refactor current upload code into React setup so resource upload working 3d #6
* [x] Resource metadata editor #12

v0.2

* [ ] Trial uppy for upload SDK (including adjust for Azure) 3d #7 
* [x] [resource] Metadata editing whilst uploading https://gatesfoundation.atlassian.net/browse/IVT-2797 (5d) #11 
* [x] [resource] Upload Progress reporting (2d) #9 

v0.3

* [x] React Table Schema editor component #13 [2d]
* [x] Link or File Upload chooser #18 [1d]
* [x] Link a file component #21 [2d]

v0.4:  Integrate this all together into a Resource editor

* [x] React App combining several lower level components into an app / flow: Upload, Edit metadata, Edit table schema, Save [1.5d] @mariorodeghiero #16 
* [x] Saving metadata #29
* [x] Integrate resource editor into CKAN (should not be too bad as done via ckanext-external-storage though more "surgery" may be needed) [2d] #38 
  * [x] Resource create #29 and https://github.com/datopian/ckanext-external-storage/issues/25 **IN PROGRESS**
  * [x] Resource edit flow #37 

v0.5 Add multiple resources at once

* [x] Multiple files add #23 [3d]
* [x] UI adjustments for multiple files #24 [2d]

v0.6

* [x] Make this work when editing an existing resource [2d] @??

v??

* [ ] Pause / resume (?) - depends on multipart support in giftless

## Analysis

* [x] What is pattern for storing and sharing state amongst components in DataPub apps and workflows?
  * Redux
  * Apollo
* [x] Are we only replacing resource create and edit stage in the CKAN Classic? Eg, in Vanilla CKAN, admin creates a dataset by creating a package first, then moves to resource create step.
  * What are we doing eventually (and where?)? Hypotheses
    * [x] We doing everything
    * We are just doing resource editor (and dropping into CKAN UI) <-- RIGHT NOW
    * We are doing several components (e.g. resource editor, dataset metadata editor) but not changing the flow

#### Low level

* FileOrLinkChooser => SharedState: FileOrLinkChosen
* Select File => SharedState: RawFile
  * uses data.js to open the file and put that Resource object in your internal state system (apollo)
* MetaEditor
* UploadProgress
* SchemaEditor
* Save

#### Parent level components and State

* ResourceManager

```javascript=
GsaApp = DatasetManager
GatesResourcEditorApp = Multi

DatasetManager
  dataset
  ui
    ...

ResourceManager(resource={}, dataset_id=None)

  state: {
    // only needed if this component saves the resource
    // (usually parent component e.g. DatasetManager will deal with saving ...)
    dataset_id: ...
    // follows frictionless Data Resource
    // if existing this will have lot of content o/w empty
    resource: {...}
    ui
      fileOrLink: file | link
      uploadComplete
      ...
  }
    
MultiResourceManager(dataset)

DatasetMetadataManager
```

### Open method - from data.js

```
open(HTML File object or URL) => if you can't open the url just give { path: url }

resource

{
  name
  title
  format
  path
  sample: // first 10/20 rows ...
  schema
}
```

### Integrate React app into CKAN Classic UI

Adding JS module - https://docs.ckan.org/en/2.8/theming/fanstatic.html - but this is for adding custom JS module. What we need is to replace current "resource editor" UI/UX with our React app.

Current flow:

```mermaid
sequenceDiagram

  Client->>CKAN: request `/datast/new`
  CKAN->>Client: HTML form + JS modules (jquery etc.)
  Client->>CKAN: Post form data to `/dataset/new`
  CKAN-->>CKAN: Create dataset in the db with state as draft
  CKAN->>Client: 302 to `/dataset/new_resource/{dataset-name}`
  Client->>CKAN: Request `/dataset/new_resource/{dataset-name}`
  CKAN->>Client: HTML form + jquery module for file uploader
  Client->>CKAN: Post form data to `/dataset/new_resource/{dataset-name}`
  CKAN-->>CKAN: Create a resource in the db + update dataset's state to active
  CKAN->>Client: 302 to `/dataset/{dataset-name}`
  Client->>CKAN: Requst `/dataset/{dataset-name}`
  CKAN->>Client: HTML of dataset page
```

**Note that when uploading file, you should post multipart/form-data.**

What do we need to replace "Resource Editor":

* Build a JS module from the React app
* Make sure you have fanstatic directory registered in the CKAN extension
* Copy the JS module(s) to the fanstatic directory
* Override 'new_resource.html' in the extension and init React module from there: `{% resource 'my_extension/bundle.js' }`

**Comment by mariorodeghiero** [comment]
@rufuspollock update:

- [x] What is the pattern for storing and sharing state amongst components in DataPub apps and workflows?
     - The pattern will be **Apollo**

cc: @anuveyatsu

**Comment by rufuspollock** [comment]
@lgilies can you work with @mariorodeghiero to create issues for v0.5 work here and make sure they are also in client backlog.

**Comment by lgilies** [comment]
@rufuspollock I created issues #23 and #24 (linked them to the description as well) and @mariorodeghiero will add the detailed content to them. We will find a way to move them to the client's backlog.

**Comment by mariorodeghiero** [comment]
Added content for Issue https://github.com/datopian/datapub/issues/24

**Comment by mariorodeghiero** [comment]
@rufuspollock @lgilies I also added some content for https://github.com/datopian/datapub/issues/23 but I have some questions. Could please take a look?

**Comment by rufuspollock** [comment]
FIXED. Everything in this now done 🍾 🚀
