### ISSUE TITLE
[epic] Resource Schema (data dictionary) editor w/ infer

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#13]
A Data Dictionary (or Table Schema) provides information about the data in a resource such as the names, types and description of the fields.

https://tech.datopian.com/publish/#adding-a-schema-data-dictionary-for-a-resource

## UX

For more, see https://tech.datopian.com/publish/#adding-a-schema-data-dictionary-for-a-resource

### Horizontal (spreadsheet like)

![](https://docs.google.com/drawings/d/e/2PACX-1vRD7XUc9iBYjEH11Zqsfrk7tAv688UTqEJMxOg4Bc-9p4Vkrcq8Oghpe5OfimfVoEzjfDRMLeUNIP63/pub?w=695&h=434)

### Vertical layout

![](https://i.imgur.com/nhb5H7Q.png)

## Acceptance

Working table schema editor as react component

UX is along lines of https://tech.datopian.com/publish/#adding-a-schema-data-dictionary-for-a-resource (but feel free to adapt/innovate)

Basic

* [x] Initialize with Data Resource including a Table Schema
  * [x] Can assume sample data is already inlined in `sample` attribute as array of dicts
* [x] Can edit and save
* [x] Basic UI: Show fields/headers and then key attributes for table schema
  * [x] title
  * [x] description (markdown?)
  * [x] type (string, int etc)
  * [x] format (optional)
* [x] Show the sample of the data either with the headers or separately from the headers
  * Probably with the headers is easier

Infer

* [x] Given Data Resource without Table Schema auto infer table schema

Bonus / future

* [ ] Show validation errors as you change types
* [x] (?) If no sample present auto generate the sample

## Tasks

* [x] Research https://github.com/datopian/import-ui
* [x] Stub a Data Resource fixture (with Table Schema)
* [x] Implement the basic editor (not sure about order of tasks so choose what you neeed)
  * [x] React component with key fields
  * [x] Create a story using storybook for displaying the schema editor
  * [x] Jest test

### JSON Schema editors

Research editors for json schema to see if we could reuse for our purposes ...

* https://github.com/YMFE/json-schema-editor-visual 527 ⭐ and updated in last 5m - based on react
* https://github.com/thomas4019/json-schema-editor - 127 ⭐ - react based

### Design

Here's a rough code sketch of how this component could work:

```jsx=
<TableSchema
  // props for initialization
  // http://frictionlessdata.io/table-schema
  // https://specs.frictionlessdata.io/table-schema/
  schema= Frictionless (f11s) Table Schema object
  // sample of the data for displaying etc
  sample= [{ a: 1, b: 2}, {a: 5, b: 10}]
  />
```

Schema example for this case:

```javascript=
schema = {
  fields: [
    {
      name: 'a',
      type: 'string',
      description: 'column a is about X',
      format: '...'
    },
    {
      name: 'b',
      type: 'integer'
    }
  ]
}
```

Inside TableSchema component:

```
TableSchema.props.schema = make a copy of passed in schema
As you edit in UI the internal schema object is updated
```

### LATER/FUTURE: For inference and having this work with data files ...

```javascript=
resource = open(HTML5 file object)

TableSchema(resource.schema, getSample(resource))
```
Use https://github.com/datopian/data.js for opening files ... (why? gives you all the metadata)

* QU: does it work with HTML5 file object? Prob not, see https://github.com/datopian/data.js/issues/49

**Comment by mariorodeghiero** [comment]
@anuveyatsu @rufuspollock I read and check the JSON schema editors available but I preferred to create my own and control the schema object via the **state** in react. The example is very simple yet but it works properly.

I think is important to decide one thing:
 -  Does the **state** of the schema and **onchange function** and "onSave function" should be in the father of the component or in the TableSchema component?

@rufuspollock what is the title? Do we need to use?

Tomorrow I pretend to add select options to the user choose.

![editor](https://user-images.githubusercontent.com/24671133/91107424-aac20880-e64b-11ea-95e8-feb6419243ab.gif)

**Comment by anuveyatsu** [comment]
Hi @mariorodeghiero this is cool 👏  

Are you referring to this spec here https://specs.frictionlessdata.io/table-schema/#descriptor ?

**Comment by rufuspollock** [comment]
@mariorodeghiero great job. Note:

* [ ] the types should come from the defined list that Table Schema has.
* [ ] We also need to add title and that's it ...

I agree we don't need json schema editors here - just build our own given how simple this.

**Comment by mariorodeghiero** [comment]
Hi @anuveyatsu I think we are up to date after our meeting today.

@rufuspollock yes, I will working to get this done and I will let you know.

**Comment by mariorodeghiero** [comment]
@rufuspollock @anuveyatsu I push some changes for:

- [x] the types should come from the defined list that Table Schema has.
- [x] We also need to add title and that's it ...

Could please confirm if the types should be this below?

```
{
  "type": [
    "string",
    "number",
    "integer",
    "boolean",
    "object",
    "array",
    "null",
    "any"
  ]
}

```

**Note**: The button save only send a console.log with the current state of the table schema.

![Screenshot from 2020-08-25 17-24-05](https://user-images.githubusercontent.com/24671133/91224003-d1d61400-e6f7-11ea-9b35-16040d199531.png)

**Comment by anuveyatsu** [comment]
@mariorodeghiero type options are listed below from the frictionlessdata spec:

* string
* number
* integer
* boolean
* object
* array
* date
* time
* datetime
* year
* yearmonth
* duration
* geopoint
* geojson
* any

**Comment by mariorodeghiero** [comment]
@anuveyatsu thanks. I will update the list of types and send a new PR.

**Comment by rufuspollock** [comment]
@anuveyatsu @mariorodeghiero is this now complete?

**Comment by mariorodeghiero** [comment]
@rufuspollock All things working only pending tests.
cc: @anuveyatsu

**Comment by rufuspollock** [comment]
@mariorodeghiero do we have *any* tests for this? What would test look like? I thought we had tests for the React component ...

**Comment by mariorodeghiero** [comment]
@rufuspollock We only created a simple test at the beginning of the datapub development.

**Comment by rufuspollock** [comment]
FIXED. We can do more tests and that will be a separate issue.
