### ISSUE TITLE
[epic] React Resource Editor (+ table schema editor + CKAN integration)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#14]
# 
New React-based app for creating and editing resources. This replaces CKAN classic resource create and edit but ONLY for ckan inistances using `ckanext-external-storage` (which we hope will soon be most or all of our CKAN instances).

Design features:

* Use React
* (Resource) Schema will now stored as attribute `schema` on a resource (as per Frictionless pattern) rather than in Data Dictionary and associated with DataStore.
* Inside React we use Frictionless spec for describing resources, table schemas etc (and convert to CKAN format at boundary)

## Acceptance

In a CKAN classic instance using ckanext-external-storage the resource editor is a React app and:

* [ ] I can upload resources (direct to cloud)
* [ ] I can edit resource metadata
* [ ] I can edit the table schema
* [ ] This is all saved to CKAN MetaStore
* [ ] This works for editing existing resources i.e. the React app can also load / get given an existing resource
* [ ] I have a migration script for migrating existing CKAN instances (i.e moving data dictionary info to `schema` attribute)

Leftovers

* [ ] Fixing up DataStore to retrieve table schema info from resource object **Is this needed? If people who upgrade to `ckanext-external-storage` also upgrade to AirCan there is no need. => Probably no need**

## Tasks

Est (remaining): 9d

* [ ] Resource upload and metadata editor #1
  * [ ] Resource upload
  * [ ] Resource metadata editor
  * [ ] Multiple resources
* [ ] Developing a React Table Schema editor component https://github.com/datopian/datapub/issues/13 [2d]
* [ ] Integrate this component into a Resource editor @anuveyatsu
  * [ ] React App combining several lower level components into an app / flow: Upload, Edit metadata, Edit table schema, Save [1.5d] @mariorodeghiero  (+ @anuveyatsu)
  * [ ] Saving metadata:
    * [ ] Convert from f11s to ckan: port to JS existing python f11s => CKAN mapper  https://github.com/frictionlessdata/frictionless-ckan-mapper [1.5d]
    * [ ] add methods to https://github.com/datopian/ckan-client-js to save a resource to CKAN [1d] @anuveyatsu 
* [ ] Make this work when editing an existing resource [2d] @??
* [ ] Integrate resource editor into CKAN (should not be too bad as done via ckanext-external-storage though more "surgery" may be needed) [1d]

## Analysis

* [ ] What is pattern for storing and sharing state amongst components in DataPub apps and workflows?
  * Redux
  * Apollo
* [ ] Are we only replacing resource create and edit stage in the CKAN Classic? Eg, in Vanilla CKAN, admin creates a dataset by creating a package first, then moves to resource create step.
  * What are we doing eventually (and where?)? Hypotheses
    * [x] We doing everything
    * We are just doing resource editor (and dropping into CKAN UI) <-- RIGHT NOW
    * We are doing several components (e.g. resource editor, dataset metadata editor) but not changing the flow

### Integrate React app into CKAN Classic UI

Adding JS module - https://docs.ckan.org/en/2.8/theming/fanstatic.html - but this is for adding custom JS module. What we need is to replace current "resource editor" UI/UX with our React app.

Current flow:

```mermaid
sequenceDiagram

  Client->>CKAN: request `/datast/new`
  CKAN->>Client: HTML form + JS modules (jquery etc.)
  Client->>CKAN: Post form data to `/dataset/new`
  CKAN-->>CKAN: Create dataset in the db with state as draft
  CKAN->>Client: 302 to `/dataset/new_resource/{dataset-name}`
  Client->>CKAN: Request `/dataset/new_resource/{dataset-name}`
  CKAN->>Client: HTML form + jquery module for file uploader
  Client->>CKAN: Post form data to `/dataset/new_resource/{dataset-name}`
  CKAN-->>CKAN: Create a resource in the db + update dataset's state to active
  CKAN->>Client: 302 to `/dataset/{dataset-name}`
  Client->>CKAN: Requst `/dataset/{dataset-name}`
  CKAN->>Client: HTML of dataset page
```

**Note that when uploading file, you should post multipart/form-data.**

What do we need to replace "Resource Editor":

* Build a JS module from the React app
* Make sure you have fanstatic directory registered in the CKAN extension
* Copy the JS module(s) to the fanstatic directory
* Override 'new_resource.html' in the extension and init React module from there: `{% resource 'my_extension/bundle.js' }`

**Comment by anuveyatsu** [comment]
Added "Integrate React app into CKAN Classic UI" section in the analysis of this issue. cc @rufuspollock @mariorodeghiero

**Comment by rufuspollock** [comment]
DUPLICATE. It was confusing to have this and #1 and i've therefore back merged this into #1.
