### ISSUE TITLE
Ability to copy table schema from existing resource in the same dataset

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#15]
When creating a new resource in a Dataset I want to be able to copy a table schema from an existing resource (if there is an existing resource) so that I don't have to re-enter the whole table schema again

## Flow

In terms of flow i imagine something like:

* Click: New resource
* Select file to upload
  * File starts uploading, various editors including schema editor appear
* There is a control (outside of schema editor) "Copy Schema over from Existing Resource" with select box with existing resources to choose from (resources for this dataset - gray out those resources (maybe with hover saying "no schema to copy") which do not have a `schema` attribute!)
  * If use choose a resource from that then you overwrite schema for the current new resource with schema from that resource selected
  * Schema editor updates
  * [Perhaps] some flash message like "Schema updated"

NB: we don't need this feature to show up on resource editing (though no harm in it being there i suppose so could have it)

## Acceptance

- [ ] When creating a table schema for a new resource I want to be able to start from an existing one so that I don't have to write everything out again
  - [ ] Default one at the dataset level OR copy from a previous resource [that you can copy over at creation time ...]
  - [ ] 

## Tasks

* [x] Mock this up in e.g. figma
* [ ] Mock a dataset object with say 2 existing resources 
  * [ ] Initiating the ResourceEditor app with a mock 
  * [ ] Handle case (or check if happens) that ResourceEditor not initiated with a Dataset - this would involve retrieving the dataset from the API using the ckan-client-js retrieve method
* [ ] Implement the widget and add to ResourceEditor app
* [ ] (Test??)

**Comment by kmanaseryan** [comment]
@rufuspollock can you write acceptance criteria and also give some context?

**Comment by kmanaseryan** [comment]
Figma Mock.
![image](https://user-images.githubusercontent.com/3371013/96586266-cf57fb00-12f1-11eb-9e73-b298080f329e.png)

**Comment by rufuspollock** [comment]
@kmanaseryan looks good. any chance of editable access on this? Main point right now:

* I don't think we need to choose to have copy schema or new schema. We can just have "copy schema from existing resource" (we always create the schema and load it like normal by inference and the copy just overwrites that). does that make sense?

**Comment by kmanaseryan** [comment]
@rufuspollock I see your point. The above two options are radio buttons so either copy or new. If it's new, then the dropdown will be disabled. Alternatively we can have a checkbox and remove New Schema option, so no radio buttons just one checkbox which will control the active state of the dropdown.

**Comment by rufuspollock** [comment]
@kmanaseryan checkbox sounds better. though maybe even that is not needed - just a label and the dropdown.

**Comment by kmanaseryan** [comment]
For follow up updates please follow https://github.com/datopian/datapub-nhs/issues/5 created in the related repository.
