### ISSUE TITLE
Integrated resource editor app in React

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#16]
React App combining several lower level components into an app / flow: Upload, Edit metadata, Edit table schema, Save

Need to mock this up a bit.

* Upload
* Metadata editor
* Schema editor

Could be stepped or all in one page (maybe hide show for some of it so it would work with multiple resources).

## Acceptance criteria

* [ ] I can use this app (with some config) to add new resources into a CKAN DMS

## Tasks

* [x] Wire components together into an overall component
* [ ] Mock up wireframe
* [ ] Implement the wireframe

**Comment by mariorodeghiero** [comment]
@rufuspollock @anuveyatsu I sent a PR with some updates in this [commit 9e0d670](https://github.com/datopian/datapub/commit/9e0d670c110e141c5fb65506d17c688a9e0de6ea) you can see the result online in 
https://datopian.github.io/datapub/?path=/story/templates--app-template

Tomorrow I pretend to improve more the save metadata and save schema process + stepper.

**Comment by anuveyatsu** [comment]
@mariorodeghiero how about enabling multiple file uploads?

**Comment by rufuspollock** [comment]
That should be separate issue. Note that foe multiple resources we prob
don't want stepped ux but have collapsible components for eg schema editor

**Comment by mariorodeghiero** [comment]
@anuveyatsu @rufuspollock Can be controlled for each file independently?
I thought in some like: when the user selects the file uploaded/uploading. The "Editor stepper" will show only the info about the file selected and the user can edit it.

**Comment by anuveyatsu** [comment]
@mariorodeghiero I think you mean the same thing as Rufus :smile: anyway let's leave the multiple files for later

**Comment by mariorodeghiero** [comment]
sounds good, let's keep with the plan

**Comment by mariorodeghiero** [comment]
@anuveyatsu @rufuspollock could please take a look https://datopian.github.io/datapub/?path=/story/templates--app-template if need something more for this issue?

I think the next step we need to fix. If hasn't a schema for the current file, we need to create a default schema?

**Comment by anuveyatsu** [comment]
@mariorodeghiero I'm not sure if there is a schema when user just uploads a file. I believe the steps are:

1. Select a file for upload
2. The app detects title and format (if possible)
3. It infers schema from the given file (assuming it's tabular)
4. Now, user can change metadata and/or schema

cc @rufuspollock

**Comment by mariorodeghiero** [comment]
added some documentation improvements, now you can click in "Docs" (in the top left) and see the documentation of the components and all status of the stories.

![Screenshot from 2020-08-31 11-48-34](https://user-images.githubusercontent.com/24671133/91733617-2bb75d80-eb80-11ea-91cd-68691f2414a7.png)

**Comment by rufuspollock** [comment]
FIXED. We have this wired up pretty nicely now.
