### ISSUE TITLE
Componentize and declare the usage

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapub#19]
At the moment, we have default setup created by CRA tool. This auto initializes the app without any arguments being passed:

```javascript
// src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```

What do we want is to be able to choose components that is needed for a project and construct the UI:

For example, in a specific project app, you may use only `FileUploader` and `MetadataEditor`:

```javascript
import React from 'react';
import { FileUploader, MetadataEditor } from 'datapub';

function MyApp() {
  return (
    < FileUploader />
    <MetadataEditor />
  );
}

export default MyApp;
```

or you can just load entire app with all default components:

```javascript
import React from 'react';
import { ResourceManager } from 'datapub';

function MyApp() {
  return (
    < ResourceManager resource={resource} />
  );
}

export default MyApp;
```

same for multi resource manager:

```javascript
import React from 'react';
import { MultiResourceManager } from 'datapub';

function MyApp() {
  return (
    <MultiResourceManager resources={resources} />
  );
}

export default MyApp;
```

## Acceptance criteria

* [ ] I can use specific components of the app in my project
* [ ] I have clear docs about the usage

## Tasks

* [ ] Refactor `/src/index.js` according to analysis
* [ ] Change the structure of the app including file names etc. to align with the analysis
* [ ] Sync with @mariorodeghiero and create a PR so that we are on the same page

## Analysis

How to refactor `/src/index.js`:

As we need to componentize this app, we need to export each component so that it can be imported and used from the client app:

```javascript
// src/index.js
export { ResourceEditor, MultiResourceEditor } from './App';
export { FileUploader } from './components/FileUploader';
export { MetadataEditor } from './components/MetadataEditor';
export { SchemaEditor } from './components/SchemaEditor';
export { ProgressBar } from './components/ProgressBar';
```

We also can have an option for users who just wants to mount this app to the HTML:

```javascript
// src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

function mountResourceEditorApp([elementId, datasetId] = ['root', undefined]) {
  if (!datasetId) {
    throw error
  }

  ReactDOM.render(
    <React.StrictMode>
      <App ... />
    </React.StrictMode>,
    document.getElementById(elementId)
  );
}
```

**Comment by anuveyatsu** [comment]
cc @rufuspollock

**Comment by rufuspollock** [comment]
@anuveyatsu looks great.
