### ISSUE TITLE
[resource] Component for Linking a Resource

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#21]
Have a component for "Link a file" in Resource add 

## Acceptance

* [ ] a form field providing a link
* [ ] When you type something in the url component and it loses focus we should bring up metadata editor and schema editor with info filled in if we can
* [ ] We should attempt to retrieve that link in the browser (using data.js)
  * [ ] show 404 if link does not work
  * [ ] Handle CORs errors gracefully
  * [ ] Use the info from data.js to populate meta and schema editors

## Tasks

**Comment by rufuspollock** [comment]
We have started but not properly wired up. https://datopian.github.io/datapub/?path=/story/templates--app-template

**Comment by rufuspollock** [comment]
@mariorodeghiero could you update here on where we are with this?

**Comment by mariorodeghiero** [comment]
we just have the UI working. Not implemented yet.

**Comment by rufuspollock** [comment]
@mariorodeghiero i think this is FIXED. Can you update with latest info.

**Comment by mariorodeghiero** [comment]
@rufuspollock No, this is fixed for **gdx**, but I think we can bring **almost** the same code and insert it here. I can help @cotts or @risenW to do it.
