### ISSUE TITLE
UI adjustments for multiple files

### ISSUE THREAD

**Issue by lgilies** [datopian/datapub#24]
When the user drags and drops multiple files, the user wants to see all the files with each status independently and when the user clicks on card status, in metadata editor expects to show the file information.

## Acceptance

- [x] User can drag & drop multiple files
- [x] User can see the upload info for all files uploading independently
- [x] User can edit the metadata information for each file independently

## Tasks

- [x] Draft design and UI flow in figma and check with client
- [x] Implement

e.g. prob something like ...

- [x] UI - Render all files in the upload status area
  - [x] Render all files in the upload info
  - [x] Show a maximum of 4 files 
  - [x] when the user create upload more than 4 files should appear a nice scroll bar in the upload area
  ~~- [ ] In the upload info area show the total of files~~
  - [x] When the upload request is a success or failure to change the progress Bar circle to success or failed
- [x] Be able to select each file uploading and edit each metadata information independently

**Comment by mariorodeghiero** [comment]
There is an issue with CSS style, after using the import components from datapub. I'm investigating what is happened.

**Comment by mariorodeghiero** [comment]
update:

After import a component from the library, when running `yarn build` generate two CSS files. Both of these CSS files should be added In ckanext-datapub be able to render external components imported.

```
{% resource 'datapub/css/2.13e0d705.chunk.css' %}
{% resource 'datapub/css/main.c6297111.chunk.css' %}
{% resource 'datapub/js/runtime-main.95a62798.js' %}
{% resource 'datapub/js/2.bfcaf294.chunk.js' %}
{% resource 'datapub/js/main.d1dbf6f8.chunk.js' %}
```

@kmanaseryan if you get the same error above, check if you are using something like this.

**Comment by rufuspollock** [comment]
@mariorodeghiero that seems a useful piece of information. Can you add that to the README of ckanext-datapub.

**Comment by rufuspollock** [comment]
@mariorodeghiero once that is done i think we can close this issue as FIXED. When doing that could you post a short screencast showing it in action (it looks really good).

**Comment by mariorodeghiero** [comment]
@rufuspollock ok I will update this on `ckanext-datapub` readme because needs to be implemented there.

**Comment by mariorodeghiero** [comment]
FIXED. Add information in ckanext-datapub how to use all chunks.
