### ISSUE TITLE
[resource] Save (updated) resource metadata to DMS backend i.e. CKAN

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#29]
Save resource metadata (including sha-256 field which indicates this is stored via giftless) into  backend (CKAN).

## Acceptance

* [x] On hitting save in resource manager resource metadata is saved to CKAN backend
* [ ] And datasets is published (change from draft state)
* [ ] And you are redirected to dataset page

## Tasks

Preliminaries in external libs

  * [x] Convert from f11s to ckan: port to JS existing python f11s => CKAN mapper  https://github.com/frictionlessdata/frictionless-ckan-mapper [1.5d] **In progress: https://github.com/datopian/frictionless-ckan-mapper-js**
  * [x] add methods to https://github.com/datopian/ckan-client-js to save a resource to CKAN [2d] https://github.com/datopian/ckan-client-js/issues/4
* [x] Update data.js to support browser file object

Work here

* [x] On resource create page call relevant methods in JS SDK to save resource to backend **DONE. But turns out there are issues**
* [x] Resource Create page: Stop calling package_update and call resource_create and only do that on when user hits save
  * [x] Have an internal method `createResource(f11sResourceMeta, datasetIdOrName)`
* [x] Rename "Save Metadata" to "Save and Publish". After saving then redirect to: `/dataset/{dataset.name}`
  * [x] Rename button
  * [x] (Continue doing resource create) AND Dataset state to `active` from `draft` and call `push` (package_update)
  * [x] Redirect to dataset page

**Comment by rufuspollock** [comment]
Added a bunch of items today:

* [x] Resource Create page: Stop calling package_update and call resource_create and only do that on when user hits save
  * [x] Have an internal method `createResource(f11sResourceMeta, datasetIdOrName)`
* [x] Rename "Save Metadata" to "Save and Publish". After saving then redirect to: `/dataset/{dataset.name}`
  * [x] Rename button
  * [x] (Continue doing resource create) AND Dataset state to `active` from `draft` and call `push` (package_update)
  * [x] Redirect to dataset page

**Comment by rufuspollock** [comment]
FIXED. All done now we hope.
