### ISSUE TITLE
Basic tests working for the app with CI

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#3]
Set up tests with Jest in the React application to test the upload flow. We use [Jest](https://jestjs.io/en/) because it is now default for React and has nice documentation, support, and tutorials.

2 kinds of tests:

* Component tests via jest
* Integration tests (via cypress) - make not be needed for simple components ...

## Acceptance

* [x] We have one or more tests of basic system
* [x] We have continuous integration with github actions i.e. tests are run on every push etc

## Tasks

* [x] Have a basic test for your first component with jest
* [x] Instructions on how to run the tests in the developer section of README
* [x] Set up github actions for jest

**Comment by mariorodeghiero** [comment]
FIXED. See the items below with screenshots. 
@rufuspollock cypres will be for the future, right?

- [x] We have one or more tests of basic system
- [x] We have continuous integration with github actions i.e. tests are run on every push etc
- [x] add badge for github actions on README

![Screenshot from 2020-08-05 21-16-55](https://user-images.githubusercontent.com/24671133/89477443-a8167680-d763-11ea-94b3-b5f8c25bdde0.png)

![Screenshot from 2020-08-05 21-37-24](https://user-images.githubusercontent.com/24671133/89477538-e90e8b00-d763-11ea-9b99-b2b8a04c875c.png)

**Comment by rufuspollock** [comment]
Yes, I've moved integration tests to #8
