### ISSUE TITLE
Report: bugs after trial of DataPub in the existing project

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datapub#31]
## Tasks

* [x] Icon for upload doesn't load @mariorodeghiero 
* [x] Progress bar - doesn't work if file already exists - stays at 0% but says upload succeeded @mariorodeghiero 
* [x] 'Save' button is disabled so I cannot edit the metadata and save @mariorodeghiero 
* [x] After resource is created following properties are missing:
  * [x] URL for resource
  * [x] Name
  * [x] Size
  * [x] Mimetype
  * [x] See example of resource_show response below
* [x] Also, a resource can be restricted (eg, public vs private) but it is something custom and it is missing in DataPub. Eg: `"restricted": "{\"level\": \"public\"}"`

```
{
"help": ".../api/3/action/help_show?name=resource_show",
"success": true,
"result": {
"cache_last_updated": null,
"package_id": "433aa98f-9dec-4052-a4b4-0b2590a9e5e8",
"datastore_active": false,
"id": "8ef6662d-5052-437c-9f5d-7704f8b5d88a",
"size": null,
"restricted": "",
"encoding": "utf-8",
"state": "active",
"schema": "{u'fields': [{u'type': u'yearmonth', u'name': u'YEAR_MONTH', u'format': u'default'}, {u'type': u'string', u'name': u'ODS_CODE', u'format': u'default'}, {u'type': u'integer', u'name': u'VMP_SNOMED_CODE', u'format': u'default'}, {u'type': u'string', u'name': u'VMP_PRODUCT_NAME', u'format': u'default'}, {u'type': u'integer', u'name': u'UNIT_OF_MEASURE_IDENTIFIER', u'format': u'default'}, {u'type': u'string', u'name': u'UNIT_OF_MEASURE_NAME', u'format': u'default'}, {u'type': u'integer', u'name': u'TOTAL_QUANITY_IN_VMP_UNIT', u'format': u'default'}], u'missingValues': [u'']}",
"dialect": "{u'quoteChar': u'\"', u'delimiter': u','}",
"hash": "c252dc3247713d7bd83c9b7a7729168273092231f736422c1a599e8dbf58a014",
"description": "",
"format": "CSV",
"last_modified": null,
"url_type": null,
"mimetype": null,
"cache_url": null,
"created": "2020-09-17T06:41:28.013104",
"url": "",
"mimetype_inner": null,
"position": 19,
"revision_id": "d6716aed-38e0-4126-9bde-ff6c244346e0",
"resource_type": null
}
}
```

**Comment by anuveyatsu** [comment]
@kmanaseryan @mariorodeghiero here is the list of issues that we've identified.

@rufuspollock most of these are pretty clear. I'd like to have some comment about the last one as it is about custom resource field (`restricted`). Here are the options I can see:

* Option 1: Explore how we can customize resource metadata fields. E.g., ability to pass `resource` dictionary that will tell us what fields are needed.
* Option 2: Create a branch and implement project specific requirements.

**Comment by mariorodeghiero** [comment]
**Update about September 17:** 
These three items are done and merged.
- [x] Icon for upload doesn't load @mariorodeghiero
- [x] Progress bar - doesn't work if file already exists - stays at 0% but says upload succeeded @mariorodeghiero
- [x] 'Save' button is disabled so I cannot edit the metadata and save @mariorodeghiero

**Comment by shevron** [comment]
@mbeilin and I just did a debugging session, we see that the following critical properties when calling `resource_create` are still missing. Without these properties `ckanext-blob-storage` will not be able to fetch resources at all:
* `sha256` (currently called "hash")
* `size` 
* `lfs_prefix` (this is currently needed, as it designates where in the LFS server the resource has been stored even if the package / org will be renamed in the future) 
* `url`
* `url_type` (should be `"upload"`). 

The the old code in `upload.js` in ckanext-blob-storage @ v0.1.2 to see exactly what fields were being sent before datapub was integrated.

**Comment by shevron** [comment]
>> URL for resource
> This is a complex one. It's not really clear how this should work in ckanext-blob-storage. For now I suggest we leave this and I will come back on this.

In the case of an uplaoded file, `url` should contain the file name (no path). This allows `ckanext-blob-storage` / `giftless` to trigger a download with the original file name retained, and also follows vanilla CKAN behavior.

**Comment by mariorodeghiero** [comment]
@shevron @mbeilin this PR https://github.com/datopian/datapub/pull/46 should fix it.
cc: @rufuspollock

**Comment by mariorodeghiero** [comment]
This is the result from resource_show after #46 

```
{
  "help": "http://localhost:5000/api/3/action/help_show?name=resource_show",
  "success": true,
  "result": {
    "cache_last_updated": null,
    "package_id": "73945c8a-2c8e-4416-bc48-13b105ec3964",
    "datastore_active": false,
    "id": "a43d0493-7c1a-498d-a309-463dfa501e53",
    "size": 212403,
    "title": "test-dataset",
    "encoding": "utf-8",
    "state": "active",
    "sha256": "8a77b78af7582cce46c8f9bab884e07d763ba148b1e26b00632ba2d29966edfc",
    "lfs_prefix": "myorg/datopian-test",
    "schema": "{u'fields': [{u'type': u'string', u'name': u'Province/State', u'format': u'default'}, {u'type': u'string', u'name': u'Country/Region', u'format': u'default'}, {u'type': u'number', u'name': u'Lat', u'format': u'default'}, {u'type': u'number', u'name': u'Long', u'format': u'default'}, {u'type': u'integer', u'name': u'1/22/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/23/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/24/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/25/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/26/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/27/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/28/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/29/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/30/20', u'format': u'default'}, {u'type': u'integer', u'name': u'1/31/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/1/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/2/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/3/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/4/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/5/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/6/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/7/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/8/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/9/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/10/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/11/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/12/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/13/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/14/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/15/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/16/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/17/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/18/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/19/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/20/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/21/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/22/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/23/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/24/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/25/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/26/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/27/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/28/20', u'format': u'default'}, {u'type': u'integer', u'name': u'2/29/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/1/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/2/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/3/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/4/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/5/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/6/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/7/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/8/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/9/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/10/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/11/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/12/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/13/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/14/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/15/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/16/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/17/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/18/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/19/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/20/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/21/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/22/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/23/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/24/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/25/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/26/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/27/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/28/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/29/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/30/20', u'format': u'default'}, {u'type': u'integer', u'name': u'3/31/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/1/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/2/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/3/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/4/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/5/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/6/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/7/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/8/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/9/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/10/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/11/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/12/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/13/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/14/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/15/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/16/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/17/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/18/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/19/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/20/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/21/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/22/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/23/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/24/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/25/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/26/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/27/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/28/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/29/20', u'format': u'default'}, {u'type': u'integer', u'name': u'4/30/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/1/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/2/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/3/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/4/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/5/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/6/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/7/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/8/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/9/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/10/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/11/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/12/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/13/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/14/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/15/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/16/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/17/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/18/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/19/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/20/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/21/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/22/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/23/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/24/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/25/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/26/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/27/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/28/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/29/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/30/20', u'format': u'default'}, {u'type': u'integer', u'name': u'5/31/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/1/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/2/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/3/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/4/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/5/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/6/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/7/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/8/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/9/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/10/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/11/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/12/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/13/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/14/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/15/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/16/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/17/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/18/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/19/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/20/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/21/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/22/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/23/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/24/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/25/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/26/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/27/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/28/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/29/20', u'format': u'default'}, {u'type': u'integer', u'name': u'6/30/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/1/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/2/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/3/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/4/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/5/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/6/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/7/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/8/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/9/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/10/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/11/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/12/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/13/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/14/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/15/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/16/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/17/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/18/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/19/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/20/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/21/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/22/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/23/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/24/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/25/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/26/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/27/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/28/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/29/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/30/20', u'format': u'default'}, {u'type': u'integer', u'name': u'7/31/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/1/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/2/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/3/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/4/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/5/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/6/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/7/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/8/20', u'format': u'default'}, {u'type': u'integer', u'name': u'8/9/20', u'format': u'default'}], u'missingValues': [u'']}",
    "dialect": "{u'quoteChar': u'\"', u'delimiter': u','}",
    "hash": "8a77b78af7582cce46c8f9bab884e07d763ba148b1e26b00632ba2d29966edfc",
    "description": "Lorem lorem",
    "format": "CSV",
    "mimetype_inner": null,
    "url_type": "upload",
    "mimetype": "text/csv",
    "cache_url": null,
    "name": "time_series_covid19_confirmed_global.csv",
    "created": "2020-09-24T12:39:15.775250",
    "url": "http://localhost:5000/dataset/73945c8a-2c8e-4416-bc48-13b105ec3964/resource/a43d0493-7c1a-498d-a309-463dfa501e53/download/time_series_covid19_confirmed_global.csv",
    "last_modified": null,
    "position": 4,
    "revision_id": "7ab1d83c-da53-4dd4-b045-cd3328ac4660",
    "resource_type": null
  }
}
```

**Comment by mariorodeghiero** [comment]
FIXED. @mbeilin  already tested `"restricted": "{\"level\": \"public\"}"` and it works.
