### ISSUE TITLE
[resource] Resource edit page integration

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#37]
Have DataPub work for resource edit as well as resource create

This issue will probably require changes both here and in ckanext-blob-storage to pass in the details of the existing resource (either just the resource id (and dataset id?) and then DataPub code looks up the resource object from the API or by passing in complete JSON object).

## Acceptance

Resource edit page works correctly

* [x] You can visit the page, edit metadata or schema and save
* [x] You can remove existing data file or link
* [x] You can then add a new one (including re-inferring schema and other metadata (??) TODO: work out correct behaviour)

## Tasks

* [x] Have DataPub take over resource edit page (ckanext-blob-storage)
  * [ ] Have DataPub passed the right info by CKAN v2 system
* [x] Add state attribute to DataPub to indicate whether in create or edit mode (create is default)
* [x] Call `resource_update` rather than resource create
* [x] Pass in the resource object
* [x] Support for removing existing resource
* [x] Redirect to dataset page on save (like for resource create)

**Comment by mariorodeghiero** [comment]
- [x] re-inferring and change metadata is **OK**

@rufuspollock 

For re-inferring and change **schema** we have a problem. Because the result of the `resource_show` for `schema` and `sample` is a string with unicode like the code below and I need this information as a JSON to be able to render in tableschema component.

```
"{u'fields': [{u'type': u'string', u'name': u'Series_reference', u'format': u'default'}, {u'type': u'number', u'name': u'Period', u'format': u'default'}, {u'type': u'integer', u'name': u'Data_value', u'format': u'default'}, {u'type': u'string', u'name': u'STATUS', u'format': u'default'}, {u'type': u'string', u'name': u'UNITS', u'format': u'default'}, {u'type': u'integer', u'name': u'MAGNTUDE', u'format': u'default'}, {u'type': u'string', u'name': u'Subject', u'format': u'default'}, {u'type': u'string', u'name': u'Group', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_1', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_2', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_3', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_4', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_5', u'format': u'default'}], u'missingValues': [u'']}"
```

I tried to manage to create a regex and parse to a JSON object into a `try catch` but it works for some contents but fails for others. So the user can't see and edit the schema for some resources.

**Solution:**

As Anuar said on the chat, maybe we can create a new CKAN api action `custom_resoruce_show` for this to return the schema as JSON not as string. Or to override `resource_show`  method in the extension.

cc: @anuveyatsu @mbeilin @Daniellappv

**Comment by mbeilin** [comment]
> * [x]  re-inferring and change metadata is **OK**
> 
> @rufuspollock
> 
> For re-inferring and change **schema** we have a problem. Because the result of the `resource_show` for `schema` and `sample` is a string with unicode like the code below and I need this information as a JSON to be able to render in tableschema component.
> 
> ```
> "{u'fields': [{u'type': u'string', u'name': u'Series_reference', u'format': u'default'}, {u'type': u'number', u'name': u'Period', u'format': u'default'}, {u'type': u'integer', u'name': u'Data_value', u'format': u'default'}, {u'type': u'string', u'name': u'STATUS', u'format': u'default'}, {u'type': u'string', u'name': u'UNITS', u'format': u'default'}, {u'type': u'integer', u'name': u'MAGNTUDE', u'format': u'default'}, {u'type': u'string', u'name': u'Subject', u'format': u'default'}, {u'type': u'string', u'name': u'Group', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_1', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_2', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_3', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_4', u'format': u'default'}, {u'type': u'string', u'name': u'Series_title_5', u'format': u'default'}], u'missingValues': [u'']}"
> ```
> 
> I tried to manage to create a regex and parse to a JSON object into a `try catch` but it works for some contents but fails for others. So the user can't see and edit the schema for some resources.
> 
> **Solution:**
> 
> As Anuar said on the chat, maybe we can create a new CKAN api action `custom_resoruce_show` for this to return the schema as JSON not as string. Or to override `resource_show` method in the extension.
> 
> cc: @anuveyatsu @mbeilin @Daniellappv

@anuveyatsu @shevron guys, any thoughts about this?
As far as I understand from @mariorodeghiero, that should be resolved in `ckan-blob-storage`, so he can move
forward in datapub. We are kind of blocked with this in NHS atm, missing the ability to update schema in resource...
cc: @Daniellappv

**Comment by anuveyatsu** [comment]
There are 2 options:

1) Quick and hacky: create `custom_resource_show` API action as mentioned in the previous comment (est 2h)
2) Change schema using https://github.com/ckan/ckanext-scheming (est 5-6h)

**Comment by mariorodeghiero** [comment]
I created an issue in ckan-blob-storage https://github.com/datopian/ckanext-blob-storage/issues/29

**Comment by mariorodeghiero** [comment]
FIXED. It was fixed in this PR https://github.com/datopian/datapub/pull/52
