### ISSUE TITLE
[resource] Integrating DataPub into existing CKAN v2 resource create and edit flow

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#38]
We need to insert DataPub resource editor into the pre-existing flow of CKAN resource editing (using https://github.com/datopian/ckanext-blob-storage to override CKAN templates). 

## Acceptance

* [x] Discovery of existing system and recommended intervention
* [x] Resource create flow done
* [x] Resource edit flow done
* [x] Documentation of any changes from current behaviour

## Tasks

* [x] Analyse how current system works in CKAN (w/o DataPub) **DONE: see below "current system"**
* [x] Create flow showing how system with DataPub will work **DONE: see below "new system"**
  * [ ] Flag any differences
* [x] Implement resource create flow
* [x] Implement resource edit flow #37

### Current system

```mermaid
graph TD

dnew[Click Dataset New]
dmeta[Dataset Metadata]

dnew --> dmeta

rnew[New Resource]

dmeta --saves dataset as draft--> rnew
rnew --finish--> dpage[Dataset Page]
rnew --add another--> rnew
rnew --previous-->dmeta


dedit[Click Edit Dataset] --> dupdate[Update Dataset Metadata]
dupdate --save/update--> dpage
dedit --resources--> res[Resources page]
res --add new--> rnew
res --click on existing resource --> redit[Resource Edit]
redit --delete--> dpage
redit --update--> resview[Resource view page]
```

### New system

```mermaid
graph TD

dnew[Click Dataset New]
dmeta[Dataset Metadata]

dnew --> dmeta

rnew[New Resource]

dmeta --saves dataset as draft--> rnew
rnew --save and publish + redirect--> dpage[Dataset Page]

dedit[Click Edit Dataset] --> dupdate[Update Dataset Metadata]
dupdate --save/update--> dpage
dedit --resources--> res[Resources page]
res --add new--> rnew
res --click on existing resource --> redit[Resource Edit]
redit --delete--> dpage
redit --update--> resview[Resource view page]
```

Resource editor

```mermaid
graph TD

start --> remove
remove --> showupload[Show Upload/Link options]
```

**Comment by rufuspollock** [comment]
@mariorodeghiero can you update and close this (i think all is done).

**Comment by mariorodeghiero** [comment]
FIXED. Create and edit flow implemented more details in #37
