### ISSUE TITLE
Research and setup storybook for this app

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#4]
Storybook is a tool that prepares a development environment for UI components. It allows you to develop and design your graphical interfaces quickly, isolated, and independently. Making it possible to define different states for components, thus documenting their states.

## Acceptance

* [x] Short summary for future of what storybook is, why to use it, and how we integrate it
* [x] Have a story for the component
* [x] Instructions in README for devs on how to use it

## Tasks

- [x] create a summary about storybook
- [x] create a story for the uploader component
- [x] add instructions in README how to use storybook

**Comment by mariorodeghiero** [comment]
Added summary in the issue description.

**Comment by mariorodeghiero** [comment]
- [x] create a summary about storybook in description of the issue
- [x] create a story for the uploader component and App template
- [x] add instructions in README how to use storybook

@rufuspollock I create the summary and I added this in the issue description. Do you want to put this on README too?

**Comment by rufuspollock** [comment]
@mariorodeghiero yes a small entry in developer section of readme explaining what this is and how we use it.

**Comment by mariorodeghiero** [comment]
@rufuspollock right, tomorrow I will update readme and after I'll close the issue.

**Comment by mariorodeghiero** [comment]
FIXED. Add a summary of the storybook in README.

- [x] create a summary about storybook
