### ISSUE TITLE
Table schema column empty 

### ISSUE THREAD

**Issue by mariorodeghiero** [datopian/datapub#55]
When the user adds a resource with empty headers broken to render the table schema component.

**Acceptance**

- [x] render the table schema component when the resource with empty headers

**Tasks**

- [x] set `column_${index}` when the `header` and `accessor` is empty
- [x] render without broken the application 

error:

![Screenshot from 2020-10-05 12-32-27](https://user-images.githubusercontent.com/24671133/95087767-7a649400-06f8-11eb-9ff2-20845d467077.png)

**Comment by mariorodeghiero** [comment]
I hope to solve it in this PR https://github.com/datopian/datapub/pull/54

cc: @mbeilin

**Comment by mariorodeghiero** [comment]
Fixed. You can check in the PR #54
