### ISSUE TITLE
Table schema scroll + css

### ISSUE THREAD

**Issue by mariorodeghiero** [datopian/datapub#56]
The table schema component renders without scroll(x) and scroll(y).

## Acceptance

- [x] add scroll(x) and scroll(y)

## Tasks

- [x] add max-width and max-height
- [x] add scroll(x) and scroll(y)
- [x] removed margin-top from app
- [x] centralize the tableschema
- [x] remove background-color from app

**Comment by mariorodeghiero** [comment]
I hope to solve it in this PR #54 

cc: @mbeilin

**Comment by mbeilin** [comment]
Still have a problem with this:
![Screenshot from 2020-10-05 18-31-18](https://user-images.githubusercontent.com/61929774/95100325-a81dfd00-0739-11eb-8178-040a1782e37f.png)

**Comment by mariorodeghiero** [comment]
This happens because the table **element** css property is set`width: 100%` in your hole project stead to create a specific class for each element. You can see in the picture below. For ckan-blob-storage and Datapub it works properly.
I created a class for the element in Datapub, try to prevent this situation.

![Screenshot from 2020-10-05 14-22-20](https://user-images.githubusercontent.com/24671133/95111688-3c766880-0716-11eb-904a-85a436d9d4e3.png)

**Comment by mariorodeghiero** [comment]
Fixed. @mbeilin confirmed it was fixed.
