### ISSUE TITLE
Refactor current file upload code into React setup for resource creation

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#6]
Integrate the [ckan3-js-sdk](https://github.com/datopian/ckan3-js-sdk) with this code and refactor so that we can upload a single file to the storage.

## Acceptance

* [x] I can upload a file to (azure) storage using the react app by dragging and dropping a file or selecting it
* [x] success/completion (or failure) is reported in some basic manner
* [ ] (?) There is a test for this (? using mocks) and cypress (?)

## Tasks

- [x] require SDK in datapub
- [x] check and provide the configuration necessary to authenticate in ckan-authz **~rufus not sure what this means**
- [x] refactor react code and make it work with the SDK uploading one file to the storage
- [x] show the request response to the user

**Comment by mariorodeghiero** [comment]
- [x] check and provide the configuration necessary to authenticate in ckan-authz

@rufuspollock I add a fetch to authenticate and get JWT token form authz into the core react code using a proxy in package.json because using the SDK I got a CORS error. Maybe we need to check with @shevron if he has any idea.

**Next steps:** 
  - Get the token and use the SDK to upload.

**Result ok:**

![Screenshot from 2020-08-07 22-34-38](https://user-images.githubusercontent.com/24671133/89699757-6ae6eb80-d8ff-11ea-92db-e688d96d20f3.png)

**Comment by mariorodeghiero** [comment]
@rufuspollock  Now all flow is working, I refactored the code and I add one more test to test the select file using jest+enzime.
Tomorrow I will add the fail/success message.

**Comment by mariorodeghiero** [comment]
FIXED. See the items below.

- [x] I can upload a file to (azure) storage using the react app by dragging and dropping a file or selecting it
- [x] success/completion (or failure) is reported in some basic manner
