### ISSUE TITLE
DataPub as component library and trialling first external DataPub based apps

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#62]
Data Publishing workflows are by their nature highly custom - though with many common components. For example, one site the resource editor may have one set of fields,  and in another they have a different set of fields (as per the discussion in 
 http://tech.datopian.com/publish/)

Our approach to this is for DataPub to provide a rich set of common **components** for building those flows and a rich set of **template** applications that show how to combine those components.

Finally, to integrate a DataPub based app into CKAN v2 one needs a CKAN extension that would insert the React app into CKAN templates in right locations. For that we are creating https://github.com/datopian/ckanext-datapub

## Where we are and what we do next

Right now the only app we have is a "demo" app in DataPub that shows off most of the components. That app is then embedded into ckanext-blob-storage

Where we want to go:

* Separate apps `datapub-xxx` for each use case
* DataPub.js has clear set of components with instruction/documentation of use (e.g. 1) run `create-react-app` 2) Change your App.js in this way etc). Also has demo (storybooked?) example apps that users of DataPub can use as a basis for their apps) 
* Separate extension `ckanext-datapub` that can be customized to integrate a given custom uploader (`ckanext-blob-storage` can probably revert to its original simplest state of just having different upload)

## Acceptance

* [x] At least one external app
* [x] DataPub code updated (if needed) to support reuse in that app
* [x] ~~DataPub "vanilla" app that does what CKAN v2.8 does as resource editor (modulo direct to cloud uploading)~~ **WONTFIX - IMO not worth this vs just using the improved editor we have**
* [x] DataPub README update with instructions on reuse
* [x] `ckanext-datapub` exists and is functional for integrating datapub based apps into CKAN v2. **https://github.com/datopian/ckanext-datapub**
* [ ] `ckanext-blob-storage` is back in its original state (? - we may want to always use DataPub going forward and not worth maintaining blob storage resource editor )
  * [ ] Update to tech.datopian.com/blob-storage/ to reflect `ckanext-datapub` approach

## Tasks

* [x] External app trial
* [x] Update DataPub documentation and code #64 
  * [x] Code updates to make this a reusable library
  * [x] README updates
  * [x] making the core app a demo/example
* [x] New CKAN extension for integration `ckanext-datapub` #63

**Comment by kmanaseryan** [comment]
@rufuspollock created this issue #64, which covers some of the points above.

**Comment by rufuspollock** [comment]
@mariorodeghiero can you update here on progress.

**Comment by mariorodeghiero** [comment]
@rufuspollock the update for #64  until now is :
 - [X] Metadata
  - [x] Choose
  - [x] InputFile
  - [x] InputUrl
  - [x] ProgressBar
  - [x] Upload
~~- [ ] ResourceEditor~~
  - [ ] TableSchema (Karlen is working)

I already tested these changes for datapub-gdx repository without TableSchema and I uploaded a file locally and it works Properly. I already push the changes and you can check the[ import here](https://github.com/datopian/datapub-gdx/blob/master/src/App.js#L5) 

cc: @risenW @kmanaseryan @anuveyatsu

**Comment by rufuspollock** [comment]
FIXED. This is all done and actively used now in external apps e.g. datapub-nhs.
