### ISSUE TITLE
Trial uppy as library for upload SDK (including adjustment for Azure)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#7]
We want to research if we can use uppy for our file upload. https://uppy.io/ is a fully featured client library for managing uploads with many adapters. Features include:

* support for many cloud storage sources out of the box
* import direct from google drive, dropbox etc
* resumable file uploads
* i18n
* recovery from crashes
* etc

## Acceptance

Answers to questions like:

* Is uppy good?
* How easy is it to use the features?
* ❗ can we integrate uppy with what we are doing? In particular, can we integrate a bespoke function for signing files for cloud storage upload?

## Tasks

* [x] Initial play around
* [ ] Can we integrate uppy with our upload signing?
  * [x] Research how lib works and 
  * [x] s3 support: This looks promising: https://uppy.io/docs/aws-s3-multipart/#prepareUploadPart-file-partData
  * [x] Google cloud storage support: see https://github.com/transloadit/uppy/issues/460
  * [x] azure support: Can we get it working with azure? See https://github.com/transloadit/uppy/issues/1591

**Comment by kmanaseryan** [comment]
### Progress
- [x] Read the blob upload [flow](https://tech.datopian.com/blob-storage/#flows)
- [x] Understood that this is also related to [Git LFS](https://github.com/datopian/giftless), this is where the upload signing and upload verification happen.  
- [x] So in brief the flow is **[get token from ckan] -> [get signed upload url] -> [upload blob] -> [verify upload]**
- [x] Uppy consists of plugins. There are plugins for destinations (where blobs are being uploaded) and plugins for sources (from where the blobs should be fetch for the uploads). 
   - [x] The only available plugin as a destination which matches with our current implementation is [AWS S3](https://uppy.io/docs/plugins/). 
   - [x] So it seems that we can use it only for S3? No, the **trick** here is that this AWS plugin can be used for other Storage providers. There are actually [S3-alternatives](https://uppy.io/docs/aws-s3/#S3-alternatives), so basically any storage provider which has identical implementation then can be used as a "aws-s3" plugin in Uppy. 
   - [x] So it seems if we override the signing related functions in **aws-s3** plugin using the auth related functions in [ckan-client-js](https://github.com/datopian/ckan-client-js), we can use the Uppy, this seems promising, but has to be tested. 



### Answers to the questions

- Is uppy good? - Yes, very well documented, good community and the number of stars is +20k
- How easy is it to use the features?  - So the features are very well documented and very intuitive. I would ask how easy we can integrate in our system? see the propoasl
- ❗ can we integrate uppy with what we are doing? In particular, can we integrate a bespoke function for signing files for cloud storage upload? - The current `aws-s3` plugin in Uppy seems very promising as you can see it has been used for different storage providers. At first glance checking the signing related functions, seems that we have all the params getting from CKAN Client JS SDK, so we just to reuse this methods for to override some functions of the plugin, but this is not 100% guaranteed, needs to be tested. Please also note that if we want to upload from remote sources then we have to have a [Campanion](https://uppy.io/docs/companion/) based proxy server 

### Proposal 

So there are `@uppy/aws-s3-multipart` and `@uppy/aws-s3` packages. We can create our own custom plugin inherited from one of this packages and use also [ckan-client-js](https://github.com/datopian/ckan-client-js) for the auth and signing urls. Then this can be used in Uppy as a custom plugin created by us.

**Comment by rufuspollock** [comment]
Great summary 👌  and update 👏

**Comment by rufuspollock** [comment]
FIXED.
