### ISSUE TITLE
File upload progress reporting

### ISSUE THREAD

**Issue by lgilies** [datopian/datapub#9]
When the user uploads a file to the storage the upload progress expects to be tracked showing a progress bar to the user with percentage done, time remaining and kb/s sec.

## Acceptance

* [x] I can track the progress when uploading the file to the blog storage
* [x] Show a circular progress bar to the user with time remaining and percentage done and kb/s sec.

![](https://i.imgur.com/l5Ffr0t.png)

## Tasks

* [x] UI - Create a circular progress bar
* [x] JS - Track the progress and populate the progress bar
* [x] JS/UI - Show percentage done, time remaining and kb/s sec

**Comment by mariorodeghiero** [comment]
@rufuspollock I did some changes in this [commit](https://github.com/datopian/datapub/commit/e17c098c0c182c72c9cbbb63ed5f36ce53fd02ba) the result you can see in the picture below.

**Comment by rufuspollock** [comment]
@mariorodeghiero this is great!

**Comment by mariorodeghiero** [comment]
@rufuspollock Check the gif below, please. I did some changes here, do you think is necessary to show kb/s? 

**Note:** I throttling my internet to "3G" to upload the file.
![upload](https://user-images.githubusercontent.com/24671133/90200539-8db94a00-ddae-11ea-8378-a016e828bb61.gif)

**Comment by rufuspollock** [comment]
@mariorodeghiero no, time remaining is great - don't think we need kb/s atm.

BTW luurve ❤️  the gif - so great for understanding the feature 👏 

I think you can close.

**Comment by mariorodeghiero** [comment]
Thanks, and yes! I agree with you.

FIXED.

- [x]  UI - Create a circular progress bar
- [x]  JS - Track the progress and populate the progress bar
- [x]  JS/UI - Show percentage done, time remaining and kb/s sec
